[program:simonai]
command=/usr/local/bin/simon
priority=16
autostart=true
autorestart=true
user=zulip
redirect_stderr=true
stdout_logfile=/var/log/zulip/simon.log
stdout_logfile_maxbytes=0
stdout_logfile_backups=0
