set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
	CREATE USER pro_api WITH PASSWORD '$POSTGRES_DB';
	CREATE DATABASE pro_api;
	GRANT ALL PRIVILEGES ON DATABASE pro_api TO pro_api;
EOSQL
