#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
	CREATE USER campus WITH PASSWORD '$POSTGRES_DB';
	CREATE DATABASE campus;
	GRANT ALL PRIVILEGES ON DATABASE campus TO campus;
EOSQL
