; defaullt supervisor config file /etc/supervisor/supervisord.conf

[unix_http_server]
file=/var/run/supervisor.sock ; (the path to the socket file)
chmod=0700                    ; sockef file mode (default 0700)

[supervisord]
user=root
logfile=/dev/stdout
logfile_maxbytes = 0
pidfile=/var/run/supervisord.pid ; (supervisord pidfile;default supervisord.pid)
childlogdir=/var/log/supervisor  ; ('AUTO' child log dir, default $TEMP)

; the below section must remain in the config file for RPC
; (supervisorctl/web interface) to work, additional interfaces may be
; added by defining them in separate rpcinterface: sections

[rpcinterface:supervisor]
supervisor.rpcinterface_factory = supervisor.rpcinterface:make_main_rpcinterface

[supervisorctl]
serverurl=unix:///var/run/supervisor.sock ; use a unix:// URL  for a unix socket

[program:app]
process_name = app-%(process_num)02d
numprocs = %(ENV_PHP_NUM_PROCS)s
environment = PHP_FPM_PORT=90%(process_num)02d
directory = /srv/app
command = %(ENV_PHP_COMMAND)s
user = www-data
autostart = true
autorestart = true
redirect_stderr = true
stdout_logfile=/var/log/supervisor/app-%(process_num)02d.log
stdout_logfile_maxbytes=50MB

[program:app-queue]
process_name = app-queue-%(process_num)02d
numprocs = 1
directory = /srv/app
command = /usr/bin/php /srv/app/artisan queue:work
user = www-data
autostart = true
autorestart = true
redirect_stderr = true
stdout_logfile=/var/log/supervisor/app-queue-%(process_num)02d.log
stdout_logfile_maxbytes=50MB

[program:devserver]
process_name = devserver-%(process_num)02d
environment = NODE_ENV=development
directory = /srv/app
command = %(ENV_DEV_SERVER_COMMAND)s
user = www-data
autostart = true
autorestart = false
redirect_stderr = true
stdout_logfile=/var/log/supervisor/devserver-%(process_num)02d.log
stdout_logfile_maxbytes=50MB

[program:nginx]
user=root
command=/usr/sbin/nginx -g 'daemon off;'
autostart=true
autorestart=true
stderr_logfile=/var/log/nginx/error.log
stdout_logfile=/var/log/nginx/access.log
stopsignal=QUIT
