; defaullt supervisor config file /etc/supervisor/supervisord.conf

[unix_http_server]
file=/var/run/supervisor.sock ; (the path to the socket file)
chmod=0700                    ; sockef file mode (default 0700)

[supervisord]
user=root
logfile=/dev/stdout
logfile_maxbytes = 0
pidfile=/var/run/supervisord.pid ; (supervisord pidfile;default supervisord.pid)
childlogdir=/var/log/supervisor  ; ('AUTO' child log dir, default $TEMP)

; the below section must remain in the config file for RPC
; (supervisorctl/web interface) to work, additional interfaces may be
; added by defining them in separate rpcinterface: sections
[rpcinterface:supervisor]
supervisor.rpcinterface_factory = supervisor.rpcinterface:make_main_rpcinterface

[supervisorctl]
serverurl=unix:///var/run/supervisor.sock ; use a unix:// URL  for a unix socket

[program:api]
process_name = api-%(process_num)02d
numprocs = 1
directory = /srv/app
command = /usr/local/bin/%(ENV_API_COMMAND)s-api
user = root
autostart = true
autorestart = true
redirect_stderr = true
stdout_logfile=/var/log/supervisor/api-%(process_num)02d.log
stdout_logfile_maxbytes=50MB

[program:api-docs]
process_name = api-docs-%(process_num)02d
numprocs = 1
directory = /srv/app/priority-api-docs
command = /usr/local/bin/%(ENV_API_COMMAND)s-docs
user = root
autostart = true
autorestart = true
redirect_stderr = true
stdout_logfile=/var/log/supervisor/api-docs-%(process_num)02d.log
stdout_logfile_maxbytes=50MB

[program:haproxy]
process_name = haproxy
numprocs = 1
directory = /srv/app
command = /usr/sbin/haproxy -db -f /etc/haproxy/cfg/haproxy.cfg
user = root
autostart = true
autorestart = true
redirect_stderr = true
stdout_logfile=/var/log/supervisor/haproxy.log
stdout_logfile_maxbytes=50MB