# {{SERVICE_NAME}} - Nuxt Application
# Generated by MechCrate Nuxt Recipe

# ─────────────────────────────────────────────────────────────────────────────
# Base Stage
# ─────────────────────────────────────────────────────────────────────────────
FROM node:{{NODE_VERSION}}-alpine AS base

RUN apk add --no-cache libc6-compat
WORKDIR /app

# ─────────────────────────────────────────────────────────────────────────────
# Development Stage
# ─────────────────────────────────────────────────────────────────────────────
FROM base AS development

# Copy package files
COPY apps/{{SERVICE_NAME}}/package*.json ./

# Install all dependencies (including dev)
RUN npm install

# Copy app source (will be overridden by volume in dev)
COPY apps/{{SERVICE_NAME}}/ .

# 3000 only. Nuxt 4 serves the Vite HMR websocket through Nitro on this same
# port, so the 24678 this used to also declare was never bound by anything inside
# the container (bd:mech-crate-1a0).
EXPOSE 3000

CMD ["npm", "run", "dev", "--", "--host", "0.0.0.0"]

# ─────────────────────────────────────────────────────────────────────────────
# Builder Stage
# ─────────────────────────────────────────────────────────────────────────────
FROM base AS builder

COPY apps/{{SERVICE_NAME}}/package*.json ./
RUN npm ci

COPY apps/{{SERVICE_NAME}}/ .

# Build the application
RUN npm run build

# ─────────────────────────────────────────────────────────────────────────────
# Production Stage
# ─────────────────────────────────────────────────────────────────────────────
FROM node:{{NODE_VERSION}}-alpine AS production

RUN apk add --no-cache libc6-compat wget
WORKDIR /app

# Create non-root user
RUN addgroup --system --gid 1001 nodejs && \
    adduser --system --uid 1001 nuxt

# Copy built application
COPY --from=builder --chown=nuxt:nodejs /app/.output /app/.output

USER nuxt

ENV NODE_ENV=production
ENV NITRO_HOST=0.0.0.0
ENV NITRO_PORT=3000

EXPOSE 3000

CMD ["node", ".output/server/index.mjs"]
