
server {
    server_name theblock.localhost;
    listen 80;

    root /srv/wp/web;

    index index.php index.html;
    access_log /var/log/nginx/local-access.log;
    error_log  /var/log/nginx/local-error.log;

    include /etc/nginx/snippets/errors.conf;
    include /etc/nginx/snippets/locations.conf;

    add_header X-Permitted-Cross-Domain-Policies none;

    location = /wp-admin {
        return 301 http://$host/wp-admin/;
    }

    location /wp-content {
        root /srv/wp;
    }
}
