
# map rss urls from /name.xml to /rss.xml?feed=name.xml
# while preserving other xml urls
map $request_uri $mapped_query_string {
    ~^/sitemap.*.xml$ $query_string;
    ~^/rss.xml\?feed=.*\.xml $query_string;
    ~^/([^\?]+\.xml)(?:\?(.*))? feed=$1&$2;
    default $query_string;
}

# map rss urls from /name.xml to /rss.xml?feed=name.xml
# while preserving other xml urls
map $request_uri $mapped_uri {
    /ping.xml /wp-json/v1/ping;
    ~^/sitemap.*.xml$ $request_uri;
    ~^/rss.xml\?feed=.*\.xml $request_uri;
    ~^/[^\?]+\.xml(\?.*)? /rss.xml?$mapped_query_string;
    default $request_uri;
}

log_format extended
    '$remote_addr - $remote_user [$time_local] '
    '"$request" $status $body_bytes_sent '
    '"$http_referer" "$http_user_agent" $http_host $server_port "$http_x_forwarded_for" $request_time';

server {
    server_name *.tblk.us *.theblockcrypto.com _;
    listen 80 default_server;

    root /srv/wp/web;

    index index.php index.html;
    access_log /var/log/nginx/tblk.us-access.log extended;
    error_log  /var/log/nginx/tblk.us-error.log;

    client_max_body_size 100M;

    include /etc/nginx/snippets/errors.conf;
    include /etc/nginx/snippets/powered-by.conf;
    include /etc/nginx/snippets/locations.conf;

    add_header X-Permitted-Cross-Domain-Policies none;

    location = /wp-admin {
        return 301 http://$host/wp-admin/;
    }

    location /wp-content {
        root /srv/wp;
    }
}
