#!/bin/sh -x

_forwardTerm () {
    echo "Caught signal SIGTERM, passing it to child processes..."
    pgrep -P $$ | xargs kill -15 2>/dev/null
    wait
    exit $?
}

trap _forwardTerm TERM

_main() {
  export NUXT_NUM_PROCS=${NUXT_NUM_PROCS:-$([[ "$CANONICAL_URL" =~ "localhost" ]] && echo 1 || echo 4)}
  export PAPI_NUM_PROCS=${PAPI_NUM_PROCS:-$([[ "$CANONICAL_URL" =~ "localhost" ]] && echo 1 || echo 4)}
  export NUXT_COMMAND=${NUXT_COMMAND:-$([[ "$CANONICAL_URL" =~ "localhost" ]] && echo "dev-server" || echo "prod-server")}
  export PAPI_COMMAND=priority-server
 
  procs="$(seq 0 $(($NUXT_NUM_PROCS - 1)))"

  for i in $procs; do
    touch "/var/log/supervisor/nuxt-0${i}.log"
    touch "/var/log/supervisor/papi-server-0${i}.log"
    chown nobody:nobody "/var/log/supervisor/nuxt-0${i}.log"
    chown nobody:nobody "/var/log/supervisor/papi-server-0${i}.log"
  done

  tail -f /var/log/supervisor/nuxt-*.log &
  tail -f /var/log/supervisor/papi-server-*.log &

  sym-merge

  echo "Starting nuxt via supervisor with: NUXT_NUM_PROCS=$NUXT_NUM_PROCS, NUXT_COMMAND=$NUXT_COMMAND ..."
  /usr/bin/supervisord -c "/etc/supervisor/conf.d/app.conf"

  echo "Configure haproxy with: IMAGE_VERSION=$IMAGE_VERSION, NUXT_NUM_PROCS=$NUXT_NUM_PROCS"
  echo "" > /etc/haproxy/cfg/servers.cfg

  for i in $procs; do
    echo ""  >> /etc/haproxy/cfg/haproxy_app.cfg
    echo "    server nuxt-0$i 127.0.0.1:300$i check" >> /etc/haproxy/cfg/haproxy_app.cfg
  done

  for i in $procs; do
    echo ""  >> /etc/haproxy/cfg/haproxy_papi.cfg
    echo "    server papi-server-0$i 127.0.0.1:400$i check" >> /etc/haproxy/cfg/haproxy_papi.cfg
  done
  echo "" > /etc/haproxy/haproxy.cfg
  cat /etc/haproxy/cfg/haproxy_*.cfg > /etc/haproxy/haproxy.cfg
  cat /etc/haproxy/haproxy.cfg
  exec haproxy -W -db -f /etc/haproxy/haproxy.cfg
}

if [ $# -eq 0 ]; then
  _main
else
  exec "$@"
fi
