{
 "title": "SQS Queue Monitoring",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "SQS Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Messages Available",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sqs_approximatenumberofmessages",
     "legendFormat": "{{queue}}"
    }
   ]
  },
  {
   "title": "Messages In Flight",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sqs_approximatenumberofmessagesnotvisible",
     "legendFormat": "{{queue}}"
    }
   ]
  },
  {
   "title": "Messages Delayed",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sqs_approximatenumberofmessagesdelayed",
     "legendFormat": "{{queue}}"
    }
   ]
  },
  { "title": "SQS Message Trends", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Total Messages per Queue",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "sqs_approximatenumberofmessages",
     "legendFormat": "{{queue}}"
    }
   ]
  },
  {
   "title": "Messages Delayed / In Flight",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "sqs_approximatenumberofmessagesdelayed",
     "legendFormat": "Delayed ({{queue}})"
    },
    {
     "expr": "sqs_approximatenumberofmessagesnotvisible",
     "legendFormat": "In Flight ({{queue}})"
    }
   ]
  }
 ]
}