#!/usr/bin/env bash
#
# Render Formula/mx.rb for unyform-ai/homebrew-tap from a published release.
#
# Usage:
#   scripts/homebrew/render-formula.sh <version> > Formula/mx.rb
#
#   version   release version without leading "v", e.g. 0.1.2. The release
#             v<version> must already be published on RELEASES_REPO with all
#             three tarballs and their .sha256 sidecars (scripts/package.sh).
#
# Environment:
#   RELEASES_REPO   GitHub repo holding the releases
#                   (default: unyform-ai/mech-crate-releases)
#   GH_TOKEN        optional; gh uses it for the asset download. The repo is
#                   public, so anonymous works but is rate-limited.
#
# Why a renderer instead of mislav/bump-homebrew-formula-action: the formula
# carries three url/sha256 pairs (macOS universal, Linux x86_64, Linux
# aarch64) and that action rewrites only the first match of each field.
# Regenerating the whole file from the release's own checksum sidecars keeps
# every platform in lockstep and makes the tap-bump job a pure function of
# the release.

set -euo pipefail

version="${1:?version required (e.g. 0.1.2, no leading v)}"
releases_repo="${RELEASES_REPO:-unyform-ai/mech-crate-releases}"
tag="v${version}"
base_url="https://github.com/${releases_repo}/releases/download/${tag}"

if [[ ! "$version" =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
  echo "error: '$version' is not a stable X.Y.Z version; the tap never points at a prerelease" >&2
  exit 1
fi

tmp="$(mktemp -d)"
trap 'rm -rf "$tmp"' EXIT

gh release download "$tag" --repo "$releases_repo" --pattern '*.sha256' --dir "$tmp" >&2

# Print the sha256 recorded in the release's sidecar for one target triple.
sha_for() {
  local triple="$1"
  local sidecar="$tmp/mx-v${version}-${triple}.tar.gz.sha256"
  if [[ ! -f "$sidecar" ]]; then
    echo "error: release $tag has no checksum sidecar for $triple" >&2
    exit 1
  fi
  local sha
  sha="$(awk '{print $1}' "$sidecar")"
  if [[ ! "$sha" =~ ^[0-9a-f]{64}$ ]]; then
    echo "error: malformed sha256 in $sidecar" >&2
    exit 1
  fi
  printf '%s' "$sha"
}

sha_mac="$(sha_for universal-apple-darwin)"
sha_linux_arm="$(sha_for aarch64-unknown-linux-musl)"
sha_linux_x86="$(sha_for x86_64-unknown-linux-musl)"

cat <<FORMULA
# Generated by scripts/homebrew/render-formula.sh in Dev916/mech-crate.
# Do not edit by hand: the tap-bump job in release.yml regenerates this file
# for every stable release.
class Mx < Formula
  desc "MechCrate CLI and MCP server for project scaffolding and infrastructure"
  homepage "https://mechcrate.dev"
  version "${version}"
  license any_of: ["Apache-2.0", "MIT"]

  on_macos do
    url "${base_url}/mx-v${version}-universal-apple-darwin.tar.gz"
    sha256 "${sha_mac}"
  end

  on_linux do
    on_arm do
      url "${base_url}/mx-v${version}-aarch64-unknown-linux-musl.tar.gz"
      sha256 "${sha_linux_arm}"
    end
    on_intel do
      url "${base_url}/mx-v${version}-x86_64-unknown-linux-musl.tar.gz"
      sha256 "${sha_linux_x86}"
    end
  end

  def install
    # The whole bundle goes into libexec so mech_crate_root() (which walks up
    # from the resolved executable looking for scripts/) lands on
    # Cellar/mx/<version>/libexec, with templates/ and bin/lib/ beside the
    # binaries exactly as in the release layout. \`mx self-update\` sees the
    # Cellar path and delegates to \`brew upgrade mx\`.
    libexec.install Dir["*"]
    bin.install_symlink libexec/"bin/mx", libexec/"bin/mx-mcp"
  end

  test do
    assert_match "mx ${version}", shell_output("#{bin}/mx --version")
  end
end
FORMULA
