#!/bin/bash

_forwardTerm () {
    echo "Caught signal SIGTERM, passing it to child processes..."
    pgrep -P $$ | xargs kill -15 2>/dev/null
    wait
    exit $?
}

trap _forwardTerm TERM

echo "Starting PHP-FPM..."
php-fpm --nodaemonize &

echo "Starting NGINX..."
exec nginx -c /etc/nginx/nginx.conf -g "daemon off;"
