services:
  campus-queue:
    volumes:
      - ../../apps/campus-lms/:/srv/app
      - campus-lms-vendor_data:/srv/app/vendor
      - campus-lms-node_modules_data:/srv/app/node_modules
      - campus-lms-storage:/srv/app/storage

volumes:
  campus-lms-vendor_data:
  campus-lms-node_modules_data:
  campus-lms-storage:
