include:
  - ./redis.yml

services:
  launchpad-news:
    container_name: launchpad-news
    depends_on:
      - redis
    image: ghcr.io/theblockcrypto/launchpad-news:${LAUNCHPAD_NEWS_IMAGE_TAG:-latest}
    env_file:
      - ../.config/.env.secrets
      - ../.config/.env.shared
      - ../.config/.env.launchpad-news
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.launchpad_news.rule=PathPrefix(`/news`)"
      - "traefik.http.services.launchpad_news.loadbalancer.server.port=3000"
    stdin_open: true
    tty: true
    working_dir: /app
