include:
  - ./redis.yml

services:
  launchpad-funding:
    container_name: launchpad-funding
    depends_on:
      - redis
    image: ghcr.io/theblockcrypto/launchpad-funding:${LAUNCHPAD_FUNDING_IMAGE_TAG:-latest}
    env_file:
      - ../.config/.env.secrets
      - ../.config/.env.shared
      - ../.config/.env.launchpad-funding
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.launchpad_funding.rule=PathPrefix(`/deals`)"
      - "traefik.http.services.launchpad_funding.loadbalancer.server.port=3000"
    stdin_open: true
    tty: true
    working_dir: /app
