include:
  - ./redis.yml

services:
  launchpad-data:
    image: ghcr.io/theblockcrypto/launchpad-data:${LAUNCHPAD_DATA_IMAGE_TAG:-latest}
    container_name: launchpad-data
    env_file:
      - ../.config/.env.secrets
      - ../.config/.env.shared
      - ../.config/.env.launchpad-data
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.launchpad_data.rule=PathPrefix(`/data`)"
      - "traefik.http.services.launchpad_data.loadbalancer.server.port=3000"
    depends_on:
      - redis
    environment:
      tty: true
      stdin_open: true
