include:
  - ./redis.yml

services:
  launchpad-research:
    container_name: launchpad-research
    depends_on:
      - redis
    image: ghcr.io/theblockcrypto/launchpad-research:${LAUNCHPAD_RESEARCH_IMAGE_TAG:-latest}
    env_file:
      - ../.config/.env.secrets
      - ../.config/.env.shared
      - ../.config/.env.launchpad-research
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.launchpad_research.rule=PathPrefix(`/research`)"
      - "traefik.http.services.launchpad_research.loadbalancer.server.port=3000"
    stdin_open: true
    tty: true
    working_dir: /app
