include:
  - ./traefik.yml

services:
  localstack:
    image: localstack/localstack:4.7
    container_name: localstack
    environment:
      - SERVICES=sqs
      - DEBUG=${DEBUG:-0}
      - DATA_DIR=/var/lib/localstack
    ports:
      - "127.0.0.1:4566:4566"
      - "127.0.0.1:4510-4559:4510-4559"
    restart: always
    volumes:
      - "../system/localstack/load:/load"
