include:
  - ./redis.yml
  - ./postgres.yml
  - ./traefik.yml

services:
  priority-api:
    container_name: priority-api
    depends_on:
      - postgres
      - redis
      - traefik
    env_file:
      - ../.config/.env.secrets
      - ../.config/.env.shared
      - ../.config/.env.priority-api
    image: ghcr.io/theblockcrypto/priority-api:${PRIORITY_API_IMAGE_TAG:-latest}
    working_dir: /srv/app
    tty: true
    stdin_open: true
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.priority-api.rule=HostRegexp(`priority-api\\..*\\.tblk\\.us|priority-api\\.theblockpro\\.localhost`)"
      - "traefik.http.routers.priority-api.entrypoints=http"
      - "traefik.http.services.priority-api.loadbalancer.server.port=80"
