services:
  rabbitmq:
    image: "rabbitmq:${RABBITMQ_IMAGE_TAG:-3.7.7}"
    restart: unless-stopped
    env_file:
      - ../.config/.env.rabbitmq
      - ../.config/.env.secrets
    volumes:
      - rabbitmq:/var/lib/rabbitmq:rw

volumes:
  rabbitmq:
