services:
  redis:
    container_name: redis
    healthcheck: &redis-healthcheck
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s
    image: valkey/valkey:8.1
    restart: always
    volumes:
      - ../../data/redis:/data

  redis-ro:
    command: ["redis-server", "--replicaof redis 6379"]
    container_name: redis-ro
    depends_on:
      - redis
    healthcheck: *redis-healthcheck
    image: valkey/valkey:8.1
    restart: unless-stopped
