include:
  - ./sqs.yml

services:
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - ../system/localstack/sqs/monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    restart: unless-stopped
    depends_on:
      - sqs-exporter

  sqs-monitoring:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3030:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    depends_on:
      - prometheus
    volumes:
      - ../system/localstack/sqs/monitoring/grafana/provisioning:/etc/grafana/provisioning
      - ../system/localstack/sqs/monitoring/grafana/dashboards:/var/lib/grafana/dashboards
    restart: unless-stopped

  sqs-exporter:
    image: ghcr.io/jmriebold/sqs-prometheus-exporter:latest
    container_name: sqs-exporter
    environment:
      - AWS_REGION=us-east-1
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
      - SQS_MONITOR_INTERVAL_SECONDS=30
      - SQS_QUEUE_URLS=http://sqs:4566/000000000000/high-priority,http://sqs:4566/000000000000/high-priority-dlq
      - AWS_ENDPOINT_URL=http://sqs:4566
    ports:
      - "9080:8080"
    depends_on:
      - sqs