include:
  - ./redis.yml
  - ./postgres.yml
  - ./launchpad-api.yml
  - ./traefik.yml

services:
  theblock-treasuries:
    image: ghcr.io/theblockcrypto/theblock-treasuries:${THEBLOCK_TREASURIES_IMAGE_TAG:-latest}
    container_name: theblock-treasuries
    depends_on:
      - redis
      - redis-ro
      - traefik
    env_file:
      - ../.config/.env.secrets
      - ../.config/.env.shared
      - ../.config/.env.theblock-treasuries
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.tt.rule=Host(`${APP_HOST}`)"
      - "traefik.http.services.tt.loadbalancer.server.port=80"
    working_dir: /srv/app
    tty: true
