include:
  - ./redis.yml
  - ./postgres.yml
  - ./launchpad-api.yml
  - ./traefik.yml

services:
  theblock.pro:
    image: ghcr.io/theblockcrypto/theblock.pro:${THEBLOCK_PRO_IMAGE_TAG:-latest}
    container_name: theblock.pro
    depends_on:
      - redis
      - redis-ro
      - traefik
    env_file:
      - ../.config/.env.secrets
      - ../.config/.env.shared
      - ../.config/.env.theblock.pro
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.tp.rule=Host(`${APP_HOST}`)"
      - "traefik.http.services.tp.loadbalancer.server.port=80"
    working_dir: /srv/app
    tty: true
