include:
  - ./redis.yml
  - ./postgres.yml
  - ./launchpad-api.yml

services:
  theblock.pro:
    ports:
      - '24678:24678'
      - '6006:6006'
      - '3000:3000'
    volumes:
      - /srv/app/node_modules
      - ../../apps/theblock.pro:/srv/app
      #- ../../libs/launchpad-core:/srv/app/node_modules/@theblockcrypto/launchpad-core:rw
      # - ../../libs/data-dashboard-charts:/srv/app/node_modules/@theblockcrypto/data-dashboard-charts
    #labels:
    #- "traefik.enable=true"
    #- "traefik.http.routers.tp.rule=PathPrefix(`/campus`)"
    #- "traefik.http.services.tp.loadbalancer.server.port=80"

    #- "traefik.http.routers.tp-devserver.entrypoints=http"
    #- "traefik.http.routers.tp-devserver.rule=PathPrefix(`/_tbp`)"

    #- "traefik.http.routers.tp-sb.entrypoints=http"
    #- "traefik.http.routers.tp-sb.rule=PathPrefix(`/sb`)"
    #- "traefik.http.services.tp-sb.loadbalancer.server.port=6006"
