services:
  weaviate:
    command:
      - --host
      - 0.0.0.0
      - --port
      - "80"
      - --scheme
      - http
    env_file:
      - ../.config/.env.weaviate
    image: cr.weaviate.io/semitechnologies/weaviate:${WEAVIATE_IMAGE_TAG:-1.33.0}
    volumes:
      - weaviate_data:/var/lib/weaviate
    restart: on-failure:0

volumes:
  weaviate_data:
