services:
  WordPress-cron:
    container_name: theblockpro-wp-cron
    image: ghcr.io/theblockcrypto/wordpress-cron:${WORDPRESS_IMAGE_TAG:-latest}
    profiles:
      - cron
    env_file:
      - ../.config/.env.secrets
      - ../.config/.env.shared
      - ../.config/.env.wordpress
