services:
  WordPress:
    volumes:
      - ../../apps/WordPress/php:/srv/wp/php
      - ../../apps/WordPress/wp-content/mu-plugins/theblock.php:/srv/wp/wp-content/mu-plugins/theblock.php
      - ../../apps/WordPress/wp-config.php:/srv/wp/wp-config.php
#      - ../../apps/WordPress/wp-content/object-cache.php:/srv/wp/wp-content/object-cache.php

volumes:
  wp-vendor:
  wp-plugins:
