#!/bin/bash

cd /srv/app

_forwardTerm () {
    echo "Caught signal SIGTERM, passing it to child processes..."
    pgrep -P $$ | xargs kill -15 2>/dev/null
    wait
    exit $?
}

trap _forwardTerm TERM

_main() {
  
  if [ -n "$DEV_MODE" ]; then
    echo "💻 💻 💻 DEV_MODE is live 💻 💻 💻"
  else
    echo "🚀 🚀 🚀 PROD_MODE is live 🚀 🚀 🚀"
  fi

  export FRONTEND_NUM_PROCS=${FRONTEND_NUM_PROCS:-1}
  export FRONTEND_COMMAND=${FRONTEND_COMMAND:-$([[ -n "$DEV_MODE" ]] && echo "server -s nuxt -D" || echo "server -s nuxt")}

  export API_NUM_PROCS=${API_NUM_PROCS:-1}
  export API_COMMAND=${API_COMMAND:-$([[ -n "$DEV_MODE" ]] && echo "dev-server-api" || echo "prod-server-api")}

  procs="$(seq 0 $(($API_NUM_PROCS - 1)))"

  mkdir -p /var/log/supervisor

  for i in $procs; do
    touch "/var/log/supervisor/api-0${i}.log"
    touch "/var/log/supervisor/frontend-0${i}.log"
    chown nobody:nogroup "/var/log/supervisor/api-0${i}.log"
    chown nobody:nogroup "/var/log/supervisor/frontend-0${i}.log"
  done

  touch "/var/log/supervisor/haproxy.log" 
  chown nobody:nogroup "/var/log/supervisor/haproxy.log"

  tail -f /var/log/supervisor/api-*.log &
  tail -f /var/log/supervisor/frontend-*.log &
  tail -f /var/log/supervisor/haproxy.log &

  echo "Starting api and haproxy via supervisor with: API_NUM_PROCS=$API_NUM_PROCS, API_COMMAND=$API_COMMAND, FRONTEND_NUM_PROCS=$FRONTEND_NUM_PROCS, FRONTEND_COMMAND=$FRONTEND_COMMAND ..."

  /usr/bin/supervisord -n -c "/etc/supervisor/conf.d/app.conf"
}

if [ $# -eq 0 ]; then
  _main
else
  exec "$@"
fi
