#!/bin/bash
#
# Initialize a new Cloudflare app for deployment
# Usage: ./cf-init-app.sh myapp.co
#

set -e

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
CYAN='\033[0;36m'
NC='\033[0m'
BOLD='\033[1m'

# Paths
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT_DIR="$(dirname "$SCRIPT_DIR")"
CF_DIR="$ROOT_DIR/infra/cloudflare"
CF_ENV_FILE="$CF_DIR/.env.cloudflare"
CF_APPS_DIR="$CF_DIR/apps"

info() { echo -e "${BLUE}ℹ${NC} $1"; }
success() { echo -e "${GREEN}✓${NC} $1"; }
warn() { echo -e "${YELLOW}⚠${NC} $1"; }
error() { echo -e "${RED}✗${NC} $1"; exit 1; }

APP_NAME="$1"

if [[ -z "$APP_NAME" ]]; then
    error "Usage: $0 <app-name> (e.g., myapp.co, pricelove.co)"
fi

# Validate app name (domain-like format)
if [[ ! "$APP_NAME" =~ ^[a-zA-Z0-9]([a-zA-Z0-9-]*[a-zA-Z0-9])?(\.[a-zA-Z]{2,})?$ ]]; then
    warn "App name '$APP_NAME' doesn't look like a domain. Proceeding anyway..."
fi

# Load configuration
if [[ ! -f "$CF_ENV_FILE" ]]; then
    error "Cloudflare not configured. Run 'make cf-setup' first."
fi
source "$CF_ENV_FILE"

if [[ -z "$CF_ACCOUNT_ID" ]]; then
    error "CF_ACCOUNT_ID not set. Run 'make cf-setup' first."
fi

APP_DIR="$CF_APPS_DIR/$APP_NAME"

# Check if already exists
if [[ -d "$APP_DIR" ]]; then
    warn "App '$APP_NAME' already exists at $APP_DIR"
    read -r -p "Overwrite? [y/N]: " overwrite
    if [[ ! "$overwrite" =~ ^[Yy] ]]; then
        echo "Aborted."
        exit 0
    fi
    rm -rf "$APP_DIR"
fi

echo -e "${CYAN}"
cat << EOF
    ╭──────────────────────────────────╮
    │  🌐 Initializing: $APP_NAME
    ╰──────────────────────────────────╯
EOF
echo -e "${NC}"

# Create app directory
mkdir -p "$APP_DIR/src"

# Sanitize app name for variable names (replace . and - with _)
APP_NAME_SAFE=$(echo "$APP_NAME" | tr '.-' '_' | tr '[:upper:]' '[:lower:]')
APP_NAME_UPPER=$(echo "$APP_NAME_SAFE" | tr '[:lower:]' '[:upper:]')

# Create worker source
info "Creating worker source..."
cat > "$APP_DIR/src/index.ts" << EOF
import { Container, getContainer } from '@cloudflare/containers';

const HEALTH_PATHS = new Set(['/_health', '/_healthz', '/_readyz']);
const DEFAULT_INSTANCE = '${APP_NAME}-ssr';
const CONTAINER_PORT = 8080;

export class ContainerDO extends Container {
  defaultPort = CONTAINER_PORT;
  sleepAfter = '10m';
  envVars = {
    NODE_ENV: 'production',
    HOST: '0.0.0.0',
    PORT: \`\${CONTAINER_PORT}\`
  };
}

interface Env {
  APP_CONTAINER: DurableObjectNamespace<ContainerDO>;
  CONTAINER_INSTANCE_ID?: string;
}

const worker = {
  async fetch(request: Request, env: Env): Promise<Response> {
    const url = new URL(request.url);
    const instanceId =
      url.searchParams.get('instance') ?? env.CONTAINER_INSTANCE_ID ?? DEFAULT_INSTANCE;
    const container = getContainer(env.APP_CONTAINER, instanceId);

    // Health endpoints
    if (HEALTH_PATHS.has(url.pathname)) {
      const state = await container.getState();
      return Response.json(
        {
          app: '${APP_NAME}',
          status: state.status,
          lastChange: new Date(state.lastChange).toISOString(),
          exitCode: 'exitCode' in state ? state.exitCode : undefined
        },
        { headers: { 'cache-control': 'no-store' } }
      );
    }

    // Container management endpoints
    if (url.pathname === '/_container/restart') {
      if (request.method !== 'POST') return new Response('Method Not Allowed', { status: 405 });
      await container.destroy();
      return new Response('Restart requested', { status: 202 });
    }

    if (url.pathname === '/_container/start') {
      if (request.method !== 'POST') return new Response('Method Not Allowed', { status: 405 });
      await container.startAndWaitForPorts({ ports: [CONTAINER_PORT] });
      const state = await container.getState();
      return Response.json({ message: 'Container started', state, instanceId });
    }

    if (url.pathname === '/_container/status') {
      const state = await container.getState();
      return Response.json({ app: '${APP_NAME}', state, instanceId });
    }

    if (url.pathname === '/_container/stop') {
      if (request.method !== 'POST') return new Response('Method Not Allowed', { status: 405 });
      await container.stop();
      return new Response('Stop signal sent', { status: 202 });
    }

    return container.fetch(request);
  }
};

export default worker;
EOF

# Create wrangler.toml
info "Creating wrangler.toml..."
cat > "$APP_DIR/wrangler.toml" << EOF
# Cloudflare Worker Configuration for ${APP_NAME}
# Generated by cf-init-app.sh

name = "${APP_NAME}-worker"
main = "src/index.ts"
compatibility_date = "2024-11-16"
account_id = "${CF_ACCOUNT_ID}"
workers_dev = true

[vars]
CONTAINER_INSTANCE_ID = "${APP_NAME}-dev"

[[containers]]
name = "${APP_NAME}"
class_name = "ContainerDO"
image = "registry.cloudflare.com/${CF_ACCOUNT_ID}/${APP_NAME}:v0.0.1"
max_instances = 5

[[durable_objects.bindings]]
name = "APP_CONTAINER"
class_name = "ContainerDO"

[[migrations]]
tag = "v1"
new_sqlite_classes = ["ContainerDO"]

# ─────────────────────────────────────────────────────────────────────────────
# Preview Environment
# ─────────────────────────────────────────────────────────────────────────────
[env.preview]
workers_dev = true

[[env.preview.containers]]
name = "${APP_NAME}"
class_name = "ContainerDO"
image = "registry.cloudflare.com/${CF_ACCOUNT_ID}/${APP_NAME}:v0.0.1"
max_instances = 3

[[env.preview.durable_objects.bindings]]
name = "APP_CONTAINER"
class_name = "ContainerDO"

# ─────────────────────────────────────────────────────────────────────────────
# Production Environment
# ─────────────────────────────────────────────────────────────────────────────
[env.production]
workers_dev = false
routes = [
  { pattern = "${APP_NAME}/*", zone_name = "${APP_NAME}" }
]

[[env.production.containers]]
name = "${APP_NAME}"
class_name = "ContainerDO"
image = "registry.cloudflare.com/${CF_ACCOUNT_ID}/${APP_NAME}:v0.0.1"
max_instances = 10

[[env.production.durable_objects.bindings]]
name = "APP_CONTAINER"
class_name = "ContainerDO"

[env.production.vars]
CONTAINER_INSTANCE_ID = "${APP_NAME}-prod"
EOF

# Create package.json
info "Creating package.json..."
cat > "$APP_DIR/package.json" << EOF
{
  "name": "${APP_NAME}-worker",
  "private": true,
  "type": "module",
  "version": "0.0.1",
  "scripts": {
    "dev": "wrangler dev",
    "deploy": "wrangler deploy",
    "deploy:preview": "wrangler deploy --env preview",
    "deploy:production": "wrangler deploy --env production",
    "typecheck": "tsc --noEmit"
  },
  "dependencies": {
    "@cloudflare/containers": "^0.0.30"
  },
  "devDependencies": {
    "@cloudflare/workers-types": "^4.20241112.0",
    "typescript": "^5.6.3",
    "wrangler": "^3.88.0"
  }
}
EOF

# Create tsconfig.json
info "Creating tsconfig.json..."
cat > "$APP_DIR/tsconfig.json" << EOF
{
  "compilerOptions": {
    "target": "ES2022",
    "module": "ES2022",
    "moduleResolution": "bundler",
    "lib": ["ES2022"],
    "types": ["@cloudflare/workers-types/2023-07-01"],
    "strict": true,
    "noEmit": true,
    "skipLibCheck": true,
    "esModuleInterop": true,
    "allowSyntheticDefaultImports": true,
    "forceConsistentCasingInFileNames": true
  },
  "include": ["src/**/*"],
  "exclude": ["node_modules"]
}
EOF

# Create app-specific Dockerfile directory if it doesn't exist
DOCKERFILE_DIR="$ROOT_DIR/docker/dockerfiles/$APP_NAME"
if [[ ! -d "$DOCKERFILE_DIR" ]]; then
    info "Creating Dockerfile template..."
    mkdir -p "$DOCKERFILE_DIR"
    cat > "$DOCKERFILE_DIR/app" << 'EOF'
# Production Dockerfile for Cloudflare Containers
# Build: docker build -f docker/dockerfiles/APP_NAME/app -t APP_NAME:v0.0.1 .

# ----- Build Stage -----
FROM node:20-alpine AS builder
WORKDIR /app

ARG APP_VERSION=0.0.1
ENV APP_VERSION=$APP_VERSION

COPY package*.json ./
RUN npm ci

COPY . .
RUN npm run build

# ----- Production Stage -----
FROM node:20-alpine AS production
WORKDIR /app

RUN addgroup -g 1001 -S nodejs && \
    adduser -S nodejs -u 1001

COPY --from=builder --chown=nodejs:nodejs /app/dist ./dist
COPY --from=builder --chown=nodejs:nodejs /app/node_modules ./node_modules
COPY --from=builder --chown=nodejs:nodejs /app/package.json ./

USER nodejs

# Cloudflare Containers use PORT 8080 by default
ENV PORT=8080
ENV HOST=0.0.0.0
ENV NODE_ENV=production

EXPOSE 8080

HEALTHCHECK --interval=30s --timeout=3s --start-period=5s \
    CMD node -e "require('http').get('http://localhost:8080/health', (r) => process.exit(r.statusCode === 200 ? 0 : 1))"

CMD ["node", "dist/index.js"]
EOF
    # Replace APP_NAME placeholder
    sed -i '' "s/APP_NAME/$APP_NAME/g" "$DOCKERFILE_DIR/app" 2>/dev/null || \
    sed -i "s/APP_NAME/$APP_NAME/g" "$DOCKERFILE_DIR/app" 2>/dev/null || true
fi

# Create app-specific env file
ENV_DIR="$ROOT_DIR/docker/.config"
if [[ ! -f "$ENV_DIR/.env.$APP_NAME_SAFE" ]]; then
    info "Creating environment config..."
    mkdir -p "$ENV_DIR"
    cat > "$ENV_DIR/.env.$APP_NAME_SAFE" << EOF
# ${APP_NAME} configuration
${APP_NAME_UPPER}_PORT=8080
${APP_NAME_UPPER}_LOG_LEVEL=info
NODE_ENV=production
EOF
fi

echo ""
success "App '${APP_NAME}' initialized!"

echo ""
echo -e "${CYAN}╭──────────────────────────────────────────────────────────╮${NC}"
echo -e "${CYAN}│${NC}  Created:                                                 ${CYAN}│${NC}"
echo -e "${CYAN}│${NC}    • $APP_DIR/                       ${CYAN}│${NC}"
echo -e "${CYAN}│${NC}    • docker/dockerfiles/$APP_NAME/app                     ${CYAN}│${NC}"
echo -e "${CYAN}╰──────────────────────────────────────────────────────────╯${NC}"
echo ""
echo "Next steps:"
echo ""
echo "  1. Configure your domain in Cloudflare DNS"
echo "     Point ${BOLD}${APP_NAME}${NC} to Cloudflare (proxied)"
echo ""
echo "  2. Update the Dockerfile for your app:"
echo "     ${BOLD}docker/dockerfiles/$APP_NAME/app${NC}"
echo ""
echo "  3. Install dependencies:"
echo "     ${BOLD}make cf-install a=$APP_NAME${NC}"
echo ""
echo "  4. Deploy to production:"
echo "     ${BOLD}make cf-deploy a=$APP_NAME${NC}"
echo ""
