#!/bin/bash
#
# Cloudflare Setup Wizard
# Collects and saves credentials for multi-app deployment
#

set -e

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
CYAN='\033[0;36m'
NC='\033[0m'
BOLD='\033[1m'

# Paths
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT_DIR="$(dirname "$SCRIPT_DIR")"
CF_DIR="$ROOT_DIR/infra/cloudflare"
CF_ENV_FILE="$CF_DIR/.env.cloudflare"
CF_APPS_DIR="$CF_DIR/apps"

info() { echo -e "${BLUE}ℹ${NC} $1"; }
success() { echo -e "${GREEN}✓${NC} $1"; }
warn() { echo -e "${YELLOW}⚠${NC} $1"; }
error() { echo -e "${RED}✗${NC} $1"; exit 1; }

echo -e "${CYAN}"
cat << 'EOF'
    ╭──────────────────────────────────╮
    │  ☁️  Cloudflare Setup Wizard      │
    ╰──────────────────────────────────╯
EOF
echo -e "${NC}"

# Create directories if needed
mkdir -p "$CF_DIR"
mkdir -p "$CF_APPS_DIR"

# Check if already configured
if [[ -f "$CF_ENV_FILE" ]]; then
    source "$CF_ENV_FILE"
    echo -e "Current configuration:"
    echo -e "  Account ID: ${BOLD}${CF_ACCOUNT_ID:-not set}${NC}"
    echo ""
    read -r -p "Reconfigure? [y/N]: " reconfigure
    if [[ ! "$reconfigure" =~ ^[Yy] ]]; then
        echo "Keeping existing configuration."
        exit 0
    fi
    echo ""
fi

# Check if logged in
echo -e "${BOLD}Step 1: Authentication${NC}"
echo ""

if npx wrangler whoami &>/dev/null; then
    CURRENT_USER=$(npx wrangler whoami 2>/dev/null | grep -oE 'email: [^ ]+' | cut -d' ' -f2 || echo "authenticated")
    success "Already logged in as: $CURRENT_USER"
else
    info "Not logged in to Cloudflare."
    read -r -p "Run 'wrangler login' now? [Y/n]: " do_login
    if [[ ! "$do_login" =~ ^[Nn] ]]; then
        npx wrangler login
        success "Login successful!"
    else
        warn "Skipping login. You'll need to login before deploying."
    fi
fi

echo ""
echo -e "${BOLD}Step 2: Account Configuration${NC}"
echo ""

# Get account ID
echo "Your Cloudflare Account ID can be found at:"
echo "  https://dash.cloudflare.com → Any zone → Overview → Account ID (right sidebar)"
echo ""
echo "Or run: npx wrangler whoami"
echo ""

# Try to auto-detect account ID
DETECTED_ACCOUNT_ID=$(npx wrangler whoami 2>/dev/null | grep -oE 'Account ID: [a-f0-9]+' | cut -d' ' -f3 || echo "")

if [[ -n "$DETECTED_ACCOUNT_ID" ]]; then
    echo -e "Detected Account ID: ${BOLD}$DETECTED_ACCOUNT_ID${NC}"
    read -r -p "Use this Account ID? [Y/n]: " use_detected
    if [[ ! "$use_detected" =~ ^[Nn] ]]; then
        CF_ACCOUNT_ID="$DETECTED_ACCOUNT_ID"
    fi
fi

if [[ -z "$CF_ACCOUNT_ID" ]]; then
    read -r -p "Enter your Cloudflare Account ID: " CF_ACCOUNT_ID
fi

if [[ -z "$CF_ACCOUNT_ID" ]]; then
    error "Account ID is required."
fi

echo ""
echo -e "${BOLD}Step 3: Optional API Token (for CI/CD)${NC}"
echo ""
echo "An API token allows automated deployments without interactive login."
echo "Create one at: https://dash.cloudflare.com/profile/api-tokens"
echo "Required permissions: Workers Scripts (Edit), Cloudflare Container Registry (Edit)"
echo ""
read -r -p "Enter API Token (or press Enter to skip): " CF_API_TOKEN

echo ""
echo -e "${BOLD}Step 4: Default Docker Platform${NC}"
echo ""
echo "Cloudflare Containers support linux/amd64 and linux/arm64."
read -r -p "Default platform [linux/amd64]: " CF_DOCKER_PLATFORM
CF_DOCKER_PLATFORM="${CF_DOCKER_PLATFORM:-linux/amd64}"

# Save configuration
echo ""
info "Saving configuration..."

cat > "$CF_ENV_FILE" << EOF
# Cloudflare Configuration
# Generated by cf-setup.sh on $(date)
#
# This file is sourced by make/cloudflare.mk
# DO NOT commit this file to version control!

# Your Cloudflare Account ID
CF_ACCOUNT_ID=$CF_ACCOUNT_ID

# Docker platform for container builds
CF_DOCKER_PLATFORM=$CF_DOCKER_PLATFORM
EOF

# Add API token if provided
if [[ -n "$CF_API_TOKEN" ]]; then
    cat >> "$CF_ENV_FILE" << EOF

# API Token for CI/CD (keep secret!)
CLOUDFLARE_API_TOKEN=$CF_API_TOKEN
EOF
fi

# Make sure .env.cloudflare is gitignored
GITIGNORE="$ROOT_DIR/.gitignore"
if [[ -f "$GITIGNORE" ]]; then
    if ! grep -q ".env.cloudflare" "$GITIGNORE"; then
        echo "" >> "$GITIGNORE"
        echo "# Cloudflare credentials" >> "$GITIGNORE"
        echo "infra/cloudflare/.env.cloudflare" >> "$GITIGNORE"
        success "Added .env.cloudflare to .gitignore"
    fi
fi

echo ""
success "Configuration saved to $CF_ENV_FILE"

echo ""
echo -e "${CYAN}╭──────────────────────────────────────────────────────────╮${NC}"
echo -e "${CYAN}│${NC}  ${GREEN}✓ Cloudflare setup complete!${NC}                            ${CYAN}│${NC}"
echo -e "${CYAN}╰──────────────────────────────────────────────────────────╯${NC}"
echo ""
echo "Next steps:"
echo ""
echo "  1. Initialize an app:"
echo "     ${BOLD}make cf-init a=myapp.co${NC}"
echo ""
echo "  2. Deploy your app:"
echo "     ${BOLD}make cf-deploy a=myapp.co${NC}"
echo ""
echo "  3. View all apps:"
echo "     ${BOLD}make cf-status${NC}"
echo ""
