#!/usr/bin/env bash
# Generate this project's development credentials.
# Usage: ./scripts/generate-secrets.sh
#
# This is the SINGLE generation point for every recipe. `scripts/init.sh` runs
# it, and `make dev` runs `init.sh` on every start — which is what makes a
# service added with `mx add` *after* `mx new` come up with real credentials
# without a hand edit.
#
# Two passes, both idempotent:
#
#   1. Fill unset credentials in docker/.config/.env.secrets (creating it from
#      .env.secrets.template on first run). "Unset" means empty or still one of
#      the __GENERATE_*__ / CHANGE_ME placeholders the templates ship. A value
#      that is already real — generated by an earlier run, or chosen by a human —
#      is never touched, so `make dev` cannot rotate credentials out from under a
#      running database.
#
#   2. Resolve `${VAR}` references across docker/.config/.env.* into literals.
#      This is not cosmetic: the compose CLI interpolates `${…}` inside an
#      `env_file` value from the compose PROJECT DIRECTORY's `.env`, never from a
#      sibling env file. `POSTGRES_PASSWORD=${DB_PASSWORD}` in `.env.db`
#      therefore arrives EMPTY in the container, and postgres refuses to
#      initialize. Literals are the only form that reaches the container.
#
# Consequence of pass 2 worth knowing: once resolved, a derived value is a copy.
# Changing DB_PASSWORD in .env.secrets later does not re-derive POSTGRES_PASSWORD
# in .env.db — blank the derived value (or delete the file and re-run) to have it
# regenerated. `make doctor` reports anything still unset.
#
# The rules for what counts as unset, which keys stay blank, and how a value is
# shaped all live in scripts/.bashrc, so doctor agrees with this script.

set -euo pipefail

source ./scripts/.bashrc

CONFIG_DIR="docker/.config"
SECRETS_FILE="$CONFIG_DIR/.env.secrets"
SECRETS_TEMPLATE="$CONFIG_DIR/.env.secrets.template"

if [ ! -d "$CONFIG_DIR" ]; then
    print_warn "No $CONFIG_DIR — nothing to generate (add a service with 'mx add' first)"
    exit 0
fi

# Each file is rewritten via a `<name>.mxtmp.$$` sibling and moved into place, so
# an interrupted run can never leave a half-written env file. Without this trap an
# interrupted run would instead leave the temp file behind, and `.env.*.mxtmp.NNN`
# matches the `.env.*` glob that doctor reports on.
trap 'rm -f "$CONFIG_DIR"/.env.*.mxtmp.$$ 2>/dev/null || true' EXIT

# ── Pass 0: the secrets file must exist ──────────────────────────────────────

if [ ! -f "$SECRETS_FILE" ]; then
    if [ -f "$SECRETS_TEMPLATE" ]; then
        cp "$SECRETS_TEMPLATE" "$SECRETS_FILE"
        print_info "Created $SECRETS_FILE from the template"
    else
        printf '# Secrets - DO NOT COMMIT THIS FILE\n' > "$SECRETS_FILE"
        print_info "Created an empty $SECRETS_FILE"
    fi
fi

# ── Pass 1: fill unset credentials ───────────────────────────────────────────

generated_keys=""
tmp_file="${SECRETS_FILE}.mxtmp.$$"
: > "$tmp_file"

while IFS= read -r line || [ -n "$line" ]; do
    case "$line" in
        '' | '#'*) printf '%s\n' "$line" >> "$tmp_file"; continue ;;
        *=*) ;;
        *) printf '%s\n' "$line" >> "$tmp_file"; continue ;;
    esac

    key="${line%%=*}"
    value="${line#*=}"

    if mech_secret_is_blank_by_design "$key" || ! mech_secret_is_unset "$value"; then
        printf '%s\n' "$line" >> "$tmp_file"
        continue
    fi

    case "$(mech_secret_kind "$key")" in
        app_key) value="$(mech_random_app_key)" ;;
        db_user | db_name) value="$(mech_db_identifier)" ;;
        random) value="$(mech_random_secret 32)" ;;
        # Not a credential — an unrelated empty setting stays empty rather than
        # getting 32 random characters it was never meant to hold.
        *) printf '%s\n' "$line" >> "$tmp_file"; continue ;;
    esac

    printf '%s=%s\n' "$key" "$value" >> "$tmp_file"
    generated_keys="$generated_keys $key"
done < "$SECRETS_FILE"

mv "$tmp_file" "$SECRETS_FILE"
chmod 600 "$SECRETS_FILE" 2>/dev/null || true

# ── Pass 2: resolve ${VAR} references into literals ──────────────────────────

# Flat "KEY=VALUE" table of everything resolved so far. Bash 3.2 (macOS) has no
# associative arrays, and these files hold a few dozen keys at most.
MECH_ENV_VALUES=""

mech_env_lookup() {
    printf '%s\n' "$MECH_ENV_VALUES" |
        awk -F'=' -v k="$1" '$1 == k { sub(/^[^=]*=/, ""); print; exit }'
}

mech_env_remember() {
    MECH_ENV_VALUES="$MECH_ENV_VALUES
$1=$2"
}

unresolved=""

# Rewrite one env file in place, substituting every ${VAR} / ${VAR:-default} it
# can, and remembering the literals for the files processed after it.
resolve_env_file() {
    local file="$1"
    local out="${file}.mxtmp.$$"
    local line key value prefix rest ref name default sub changed

    : > "$out"
    while IFS= read -r line || [ -n "$line" ]; do
        case "$line" in
            '' | '#'*) printf '%s\n' "$line" >> "$out"; continue ;;
            *=*) ;;
            *) printf '%s\n' "$line" >> "$out"; continue ;;
        esac

        key="${line%%=*}"
        value="${line#*=}"
        changed="false"

        while :; do
            case "$value" in
                *'${'*'}'*) ;;
                *) break ;;
            esac

            prefix="${value%%'${'*}"
            rest="${value#*'${'}"
            ref="${rest%%'}'*}"
            rest="${rest#*'}'}"

            name="$ref"
            default=""
            case "$name" in
                *:-*)
                    default="${name#*:-}"
                    name="${name%%:-*}"
                    ;;
            esac

            sub="$(mech_env_lookup "$name")"
            [ -n "$sub" ] || sub="$default"

            if [ -z "$sub" ]; then
                # Nothing to put here. Leaving the reference in place keeps the
                # breakage visible (an empty value would look deliberate) and
                # stops this loop from spinning.
                unresolved="$unresolved $file:$key(\${$ref})"
                break
            fi

            value="${prefix}${sub}${rest}"
            changed="true"
        done

        if [ "$changed" = "true" ]; then
            printf '%s=%s\n' "$key" "$value" >> "$out"
        else
            printf '%s\n' "$line" >> "$out"
        fi

        case "$value" in
            *'${'*) ;;                       # still a reference: not a literal
            *) mech_env_remember "$key" "$value" ;;
        esac
    done < "$file"

    mv "$out" "$file"
}

# Order matters: .env.secrets holds the roots, .env.shared derives from it, and
# every per-service file derives from both.
ordered_files=""
for candidate in "$SECRETS_FILE" "$CONFIG_DIR/.env.shared"; do
    [ -f "$candidate" ] && ordered_files="$ordered_files $candidate"
done
shopt -s nullglob
for candidate in "$CONFIG_DIR"/.env.*; do
    case "$candidate" in
        *.template | "$SECRETS_FILE" | "$CONFIG_DIR/.env.shared") continue ;;
    esac
    [ -f "$candidate" ] && ordered_files="$ordered_files $candidate"
done
shopt -u nullglob

for file in $ordered_files; do
    resolve_env_file "$file"
done

# ── Report ───────────────────────────────────────────────────────────────────

if [ -n "$generated_keys" ]; then
    print_success "Generated dev credentials in $SECRETS_FILE:$generated_keys"
    print_info "Dev values only. Keep the file out of version control (it is gitignored)."
else
    print_info "Credentials already set in $SECRETS_FILE — nothing to generate"
fi

if [ -n "$unresolved" ]; then
    print_warn "These env values reference a variable nothing defines:"
    for item in $unresolved; do
        echo "    - $item"
    done
    print_warn "Compose cannot resolve an env_file reference from a sibling env file,"
    print_warn "so these arrive EMPTY in the container. Set the referenced key in"
    print_warn "$SECRETS_FILE (or $CONFIG_DIR/.env.shared) and re-run 'make init'."
fi
