#!/usr/bin/env bash
# Generate secure secrets for {{SERVICE_NAME}}
# Generated by MechCrate Laravel Recipe

set -euo pipefail

SECRETS_FILE="docker/.config/.env.secrets"

# Generate secure random password (32 chars, alphanumeric)
generate_password() {
    LC_ALL=C tr -dc 'A-Za-z0-9' < /dev/urandom | head -c 32
}

# Generate Laravel-style app key (base64 encoded 32 bytes)
generate_app_key() {
    echo "base64:$(openssl rand -base64 32)"
}

if [[ -f "$SECRETS_FILE" ]]; then
    echo "🔐 Generating secure secrets..."
    
    # Replace password placeholder
    DB_PASSWORD=$(generate_password)
    sed -i.bak "s/__GENERATE_DB_PASSWORD__/${DB_PASSWORD}/" "$SECRETS_FILE"
    
    # Replace app key placeholder  
    APP_KEY=$(generate_app_key)
    # Escape special chars for sed
    APP_KEY_ESCAPED=$(echo "$APP_KEY" | sed 's/[&/\]/\\&/g')
    sed -i.bak "s/__GENERATE_APP_KEY__/${APP_KEY_ESCAPED}/" "$SECRETS_FILE"
    
    # Cleanup backup files
    rm -f "${SECRETS_FILE}.bak"
    
    echo "✅ Secrets generated in $SECRETS_FILE"
    echo "   ⚠️  Keep this file secure and DO NOT commit to git"
else
    echo "❌ Secrets file not found: $SECRETS_FILE"
    exit 1
fi
